spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yacobasch/spring-cloud-clients-config.git
          ignore-local-ssh-settings: true
          host-key: AAAAB3NzaC1yc2EAAAADAQABAAACAQDHnwgtchmFai+Hia+PKrCHIa/Md7sWZIQLIb8AGu2iisdsB2PXtBnjuzminPNKq3t8Tx+Ik1bjufO5jjX/tfAWiI4njRYud35SGjTf9U9WgqqdXKXcUf1Pvh7lPsrnwuV1/hZ1HExhL3ryBFoP+/vQ/YoTR4NdQy6GDQpbXOTSaVgw4NKXwMuT0+EXLsDBdtQHIS35mKnTK3bYNSqn/kn6RaT21VAfC3RpwqzjE4xRqmgGstRkY+aTA5ZxaTPWw/nzSuignub6dkw/wp2fsyILiqaAMyonh6oBHJqV0h+0Ivq2lk8IS1ZGsoODESaexvxkwtS9yRiykobGe4VX2/rIb6ZTMf2NQJuH0i86HSJQq3jmxOL/ccxZ57iabedI5czDTvmkWJOTXQhiQ2LNeji384JzLHditWCI+VJjRhCpQBM/DbBYyc9ziJCxAcgJunhd5lFYwq/74waG5QnVWgwwP8h2rvHA1Y/WWgDnM6WI8fjxFV0XVWlyWXplkbn5eWgtBjkZJCgw0D8MEuqIaIvU1LkTXGOI/PxPwURjKSh14144jvdjjuJ90ywddIincyniW14w0mOPWdAP69F/4KNgzWKeAg1X8VEIzT1dZVD3S76CYiCKhUAnBYCO3cMvwO5XSiDiUVvf2vIB/Pg8ygPEdNWcSOYQOGTfpl3bWA/iZQ== ya.tsegaye@gmail.com
          host-key-algorithm: ssh-rsa
          private-key: |
                        -----BEGIN RSA PRIVATE KEY-----
                        MIIJKQIBAAKCAgEAx58ILXIZhWovh4mvjyqwhyGvzHe7FmSECyG/ABrtoorHbAdj
                        17QZ47s5opzzSqt7fE8fiJNW47nzuY41/7XwFoiOJ40WLnd+Uho03/VPVoKqnVyl
                        3FH9T74e5T7K58Lldf4WdRxMYS968gRaD/v70P2KE0eDXUMuhg0KW1zk0mlYMODS
                        l8DLk9PhFy7AwXbUByEt+Zip0yt22DUqp/5J+kWk9tVQHwt0acKs4xOMUapoBrLU
                        ZGPmkwOWcWkz1sP580rooJ7m+nZMP8Kdn7MiC4qmgDMqJ4eqARyaldIftCL6tpZP
                        CEtWRrKDgxEmnsb8ZMLUvckYspKGxnuFV9v6yG+mUzH9jUCbh9IvOh0iUKt45sTi
                        /3HMWee4mm3nSOXMw075pFiTk10IYkNizXo4t/OCcyx3YrVgiPlSY0YQqUATPw2w
                        WMnPc4iQsQHICbp4XeZRWMKv++MGhuUJ1VoMMD/Idq7xwNWP1loA5zOliPH48RVd
                        F1Vpcll6ZZG5+XloLQY5GSQoMNA/DBLqiGiL1NS5E1xjiPz8T8FEYykodeNeOI73
                        Y47ifdMsHXSIp3Mp4lteMNJjj1nQD+vRf+CjYM1ingINV/FRCM09XWVQ90u+gmIg
                        ioVAJwWAjt3DL8DuV0og4lFb39ryAfz4PMoDxHTVnEjmEDhk36Zd21gP4mUCAwEA
                        AQKCAgBOYYZveb7FoQUanhh+CZAY70Q878JZL4ydZlm969TlHsLhCyHL/56uycP+
                        ssvgxOaOz+6czOWwM0Kc2Fchmcm0v1e59e8AvdCu4jVivsqxOEtP0KIbmWHyXr94
                        2igHyoIYy3T79OmUu3T19Hl8jz+4NuVxXoIZK5jn79TiPN5oNA752j02cvA8klRu
                        qt/q1wK37fJEcAo2rXlTucSPBAz+JTx54xY7ql7CbDtASlutcVC5WJyG8qcFkMIQ
                        s/Mz3+2T9xTShLJDJBIacws7OrYifAWWjwB9VwqMtzOHomLqc1WoPeq4YgR1bACx
                        hRl5/L37vniUMJLvAxPCeZvI/MpCGczYmnlkE0mKtXo/CzQyyHoTVDuW6N++LhFQ
                        MQh5ISNfiGoIKCqi+SYMKQplBrXDwb45JcBWgbtHkZFK1JKE9JmxF02R1FPOnE3V
                        Pm+nPgPeo3qRyDxflrZK7ct25X5xRwH/bHryTou/pi94CyrtrzAEd2hcuM08bPBu
                        DlADh9P4ZXVDWXAzYKTHfiDxxsnZPNLIT0w5a+uFP6mR8Tp1K7Y4xj7y8gjST60r
                        QfCgh2zjUX8HEZlMPRo8Ras/RuJxI/15WO94KjvGY6fzuaqTguRmNUQ367UEBjiP
                        eTmjVQwRpCDB5bgXvqP3mgtDb5cm+w4SyHB2AcQ/O+FQ8sqyPQKCAQEA6+PjZYJE
                        gfLymRlPLun+xo8w/e12C/ZOwLfDwJJlRzu0uNuXLxYMm37GXlJCFS4UYwv5l57O
                        SlYG7ABRu73JHwteoArzAL+EiALcAbhB6jQASGbfabKiFGje9hD6PmCv+Ot5nM1Z
                        9WCRd/st10Zh0eLypzTI7y0KjVNrc5jX7awkynUckjvJd8GUx0IadwkhpmXVgynY
                        fRDc28oU1RSoS9KDXrHX6vmIYL8Kzxhn8dL4zZ/msHy2xkXjYMFrHFLKXmmE6Bn9
                        SdicHwgMOYsH0Xe4jWeuvqzfWOZMtyNnLMy2xh4lavkGsOiecw0DFRRcFyNaU3NZ
                        12kV82RT0BDLDwKCAQEA2KOaVaYlXysf7qIDv0L0bE0LweVwXPxN4zXme0PbIymo
                        T1RahKikGIFokg9wiH/a85P7k4m3hmk2hqREeh/YaG7vMRBwrglJ6zDKOTnGiyAJ
                        swi79BosPjKEJgWsIe8aJyKkck8SglTpW+r7EChtujVLciiLMR9Qd4iHvpXJWwhS
                        1OS37frM/TkCoe9xBSRt7xp5paXhUxfbPhG+P70waCr+z7dQABLRXpML1J/dsWAy
                        V3jI95uZOz5k2gR2R2gTSl34eg2bUjlQ8LgkwWw1t9FT4IlVYndO2DhZoYtfvImU
                        fwM+uIEtFLXZtGjRcJ/LqwObTKwo1Pp2+kTR6elLSwKCAQEAmj4gAc8FRsd6VBuV
                        iEKfQmx9B30PNFExO5itmizfpo1m5X1IxRQw2Dg0M5ar+TdxQzagVMEVeMv5qLWo
                        vA8kBHWlwRaHwNR6L4lXHJTEHQU1riH+MhoJGzlbmSCO0NzeE/C9S4eHLAih9gc6
                        +UnfSqOQMT81qBcWkEScvTCS+KkYQX4EWaZYXUMqKoSR04YYB7sMusBQ+65cDCd+
                        KbphNXsIRZIacl4KC+C/i50U0q413BaTfJF/3fPy8uBmTlXgV429xxq/YVsO8seL
                        XtEHIrOa7HOActONE487WIEAxO1zEebCZslA08q3WNmIS29NrB+Ev45sj4r6PHU8
                        zI8+hwKCAQBBZQlmh1PKqZLnDwMAji6ILq245xCHESZVyuR7Gx2gPKfw4m68kseO
                        Gio9xOlcWvP2CRqtC6pZqZLrC9Ub5FcIF0yey+6nqmgk1cKFibo0LwSehalu4yOt
                        1sPrUlUGnU2QuLVZSCM3MniK5aDJ3NpallHi8PgraN96Zb1MO5zfnOCcITqgXM/a
                        NIZl6Yh9W+TPg3drGGqvEYl98A804GAnYasveo9spkGLQeoVUfiy3W3016IalF6p
                        8oixAx3NKk6AaWNjPI5BQMn9ECkQNiD1Dvw50Fr08Tzcqg3sZM0OdZ1cxdb+DQhV
                        sxs3iViHncT2J42OlH1y5PRbUcDn0iOHAoIBAQC+2J4GMKelQ/5GTDXVzwBO4yjr
                        0/8fCxN9a1iIRl1gb3y6zvxKysOI+F3QX3h/7xnFBikVA/vhKdX/SNeNuF1HXh1R
                        nDapD/xsW5QJEPeuxThDFLwqEoqPUN9FSMz3xdXIM/JK5yZz82ad/9uUsAoIMB2D
                        Pet1nJWfRdtk4Obr89vOQ968YcHbycBTpfQFa1K8Y1cwJ2vWSje/rsTKvAzhzdSq
                        qG8K4SAbKglXTP8dGB5o5PlW0ajCtfYlBTLl60czmSqpkOHm/VqnntHN7f7s5z1M
                        TIHiecN8BzFvZxd9fznlqfH7uUN0rC3gzdyQQnLQVpZvoYhUIP2bU7SYq/VC
                        -----END RSA PRIVATE KEY-----